<a href="https://colab.research.google.com/github/MaloTheBigmalo/BridgeToSuccess/blob/master/testPython.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import matplotlib.pyplot as plt
import numpy as np

In [3]:
mat1 = np.array([

                 [-76,2,-2,0,7],
                 [-3,12,14,15,3],
                 [6,-7,4,14,13]

])

In [4]:
mat1

array([[-76,   2,  -2,   0,   7],
       [ -3,  12,  14,  15,   3],
       [  6,  -7,   4,  14,  13]])

In [6]:
element1 = mat1[1,2] #élément ligne 2 et colonne 3 = 14
print(element1)

14


In [9]:
element2 = mat1[[1,2]] # Faire une liste pour afficher la sous matrice ligne 2 jusque 3
print(element2)

[[-3 12 14 15  3]
 [ 6 -7  4 14 13]]


In [28]:
idx1 = np.ix_([0,2],[2,4]) # np.ix_ est magique pour soustraire les lignes et les
element3 =mat1[idx1]      # colonnes d'une matrice
print(element3)            # attention idx1 est un tuple,la cross index doit être 1 dimension

[[-2  7]
 [ 4 13]]


In [12]:
mat1

array([[-76,   2,  -2,   0,   7],
       [ -3,  12,  14,  15,   3],
       [  6,  -7,   4,  14,  13]])

In [36]:
mask = mat1 > 0

In [37]:
type(mask)

numpy.ndarray

In [38]:
print(mask)

[[False  True False False  True]
 [False  True  True  True  True]
 [ True False  True  True  True]]


In [39]:
print(mat1[mask])

[ 2  7 12 14 15  3  6  4 14 13]


In [48]:
result = np.where(mat1 > 0, mat1, np.nan)
print(result)

[[nan  2. nan nan  7.]
 [nan 12. 14. 15.  3.]
 [ 6. nan  4. 14. 13.]]


In [47]:
mat1

array([[-76,   2,  -2,   0,   7],
       [ -3,  12,  14,  15,   3],
       [  6,  -7,   4,  14,  13]])

In [49]:
import os

In [50]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [54]:
!ls /content/drive/MyDrive/data


Auto.csv	 College.csv	  Khan_ytest.csv   Publication.csv
Auto.data	 Credit.csv	  Khan_ytrain.csv  Smarket.csv
Bikeshare.csv	 Default.csv	  NCI60data.npy    Wage.csv
Boston.csv	 Fund.csv	  NCI60labs.csv    Weekly.csv
BrainCancer.csv  Hitters.csv	  NYSE.csv
Caravan.csv	 Khan_xtest.csv   OJ.csv
Carseats.csv	 Khan_xtrain.csv  Portfolio.csv


In [55]:
import pandas as pd


In [56]:
Auto = pd.read_csv('/content/drive/MyDrive/data/Auto.csv')