<a href="https://colab.research.google.com/github/MaloTheBigmalo/BridgeToSuccess/blob/master/TestPythonStat.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import matplotlib.pyplot as plt
import numpy as np

In [3]:
mat1 = np.array([

                 [-76,2,-2,0,7],
                 [-3,12,14,15,3],
                 [6,-7,4,14,13]

])

In [4]:
mat1

array([[-76,   2,  -2,   0,   7],
       [ -3,  12,  14,  15,   3],
       [  6,  -7,   4,  14,  13]])

In [6]:
element1 = mat1[1,2] #élément ligne 2 et colonne 3 = 14
print(element1)

14


In [9]:
element2 = mat1[[1,2]] # Faire une liste pour afficher la sous matrice ligne 2 jusque 3
print(element2)

[[-3 12 14 15  3]
 [ 6 -7  4 14 13]]


In [28]:
idx1 = np.ix_([0,2],[2,4]) # np.ix_ est magique pour soustraire les lignes et les
element3 =mat1[idx1]      # colonnes d'une matrice
print(element3)            # attention idx1 est un tuple,la cross index doit être 1 dimension

[[-2  7]
 [ 4 13]]


In [12]:
mat1

array([[-76,   2,  -2,   0,   7],
       [ -3,  12,  14,  15,   3],
       [  6,  -7,   4,  14,  13]])

In [36]:
mask = mat1 > 0

In [37]:
type(mask)

numpy.ndarray

In [38]:
print(mask)

[[False  True False False  True]
 [False  True  True  True  True]
 [ True False  True  True  True]]


In [39]:
print(mat1[mask])

[ 2  7 12 14 15  3  6  4 14 13]


In [48]:
result = np.where(mat1 > 0, mat1, np.nan)
print(result)

[[nan  2. nan nan  7.]
 [nan 12. 14. 15.  3.]
 [ 6. nan  4. 14. 13.]]


In [47]:
mat1

array([[-76,   2,  -2,   0,   7],
       [ -3,  12,  14,  15,   3],
       [  6,  -7,   4,  14,  13]])

In [49]:
import os

In [50]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [54]:
!ls /content/drive/MyDrive/data


Auto.csv	 College.csv	  Khan_ytest.csv   Publication.csv
Auto.data	 Credit.csv	  Khan_ytrain.csv  Smarket.csv
Bikeshare.csv	 Default.csv	  NCI60data.npy    Wage.csv
Boston.csv	 Fund.csv	  NCI60labs.csv    Weekly.csv
BrainCancer.csv  Hitters.csv	  NYSE.csv
Caravan.csv	 Khan_xtest.csv   OJ.csv
Carseats.csv	 Khan_xtrain.csv  Portfolio.csv


In [55]:
import pandas as pd


In [58]:
Auto = pd.read_csv('/content/drive/MyDrive/data/Auto.csv')

In [59]:
Auto.head()

mpg  cylinders  displacement  horsepower  weight  acceleration  year  \
0  18.0          8         307.0         130    3504          12.0    70   
1  15.0          8         350.0         165    3693          11.5    70   
2  18.0          8         318.0         150    3436          11.0    70   
3  16.0          8         304.0         150    3433          12.0    70   
4  17.0          8         302.0         140    3449          10.5    70   

   origin                       name  
0       1  chevrolet chevelle malibu  
1       1          buick skylark 320  
2       1         plymouth satellite  
3       1              amc rebel sst  
4       1                ford torino

In [60]:
Auto.tail()

mpg  cylinders  displacement  horsepower  weight  acceleration  year  \
387  27.0          4         140.0          86    2790          15.6    82   
388  44.0          4          97.0          52    2130          24.6    82   
389  32.0          4         135.0          84    2295          11.6    82   
390  28.0          4         120.0          79    2625          18.6    82   
391  31.0          4         119.0          82    2720          19.4    82   

     origin             name  
387       1  ford mustang gl  
388       2        vw pickup  
389       1    dodge rampage  
390       1      ford ranger  
391       1       chevy s-10

In [61]:
Auto2 = pd.read_csv('/content/drive/MyDrive/data/Auto.data', delim_whitespace=True)

/tmp/ipython-input-1717124911.py:1: FutureWarning: The 'delim_whitespace' keyword in pd.read_csv is deprecated and will be removed in a future version. Use ``sep='\s+'`` instead
  Auto2 = pd.read_csv('/content/drive/MyDrive/data/Auto.data', delim_whitespace=True)


In [62]:
Auto2.head()

mpg  cylinders  displacement horsepower  weight  acceleration  year  \
0  18.0          8         307.0      130.0  3504.0          12.0    70   
1  15.0          8         350.0      165.0  3693.0          11.5    70   
2  18.0          8         318.0      150.0  3436.0          11.0    70   
3  16.0          8         304.0      150.0  3433.0          12.0    70   
4  17.0          8         302.0      140.0  3449.0          10.5    70   

   origin                       name  
0       1  chevrolet chevelle malibu  
1       1          buick skylark 320  
2       1         plymouth satellite  
3       1              amc rebel sst  
4       1                ford torino

In [63]:
Auto.head()

mpg  cylinders  displacement  horsepower  weight  acceleration  year  \
0  18.0          8         307.0         130    3504          12.0    70   
1  15.0          8         350.0         165    3693          11.5    70   
2  18.0          8         318.0         150    3436          11.0    70   
3  16.0          8         304.0         150    3433          12.0    70   
4  17.0          8         302.0         140    3449          10.5    70   

   origin                       name  
0       1  chevrolet chevelle malibu  
1       1          buick skylark 320  
2       1         plymouth satellite  
3       1              amc rebel sst  
4       1                ford torino

In [65]:
Auto2['horsepower']

0      130.0
1      165.0
2      150.0
3      150.0
4      140.0
       ...  
392    86.00
393    52.00
394    84.00
395    79.00
396    82.00
Name: horsepower, Length: 397, dtype: object

In [66]:
np.unique(Auto2['horsepower' ])

array(['100.0', '102.0', '103.0', '105.0', '107.0', '108.0', '110.0',
       '112.0', '113.0', '115.0', '116.0', '120.0', '122.0', '125.0',
       '129.0', '130.0', '132.0', '133.0', '135.0', '137.0', '138.0',
       '139.0', '140.0', '142.0', '145.0', '148.0', '149.0', '150.0',
       '152.0', '153.0', '155.0', '158.0', '160.0', '165.0', '167.0',
       '170.0', '175.0', '180.0', '190.0', '193.0', '198.0', '200.0',
       '208.0', '210.0', '215.0', '220.0', '225.0', '230.0', '46.00',
       '48.00', '49.00', '52.00', '53.00', '54.00', '58.00', '60.00',
       '61.00', '62.00', '63.00', '64.00', '65.00', '66.00', '67.00',
       '68.00', '69.00', '70.00', '71.00', '72.00', '74.00', '75.00',
       '76.00', '77.00', '78.00', '79.00', '80.00', '81.00', '82.00',
       '83.00', '84.00', '85.00', '86.00', '87.00', '88.00', '89.00',
       '90.00', '91.00', '92.00', '93.00', '94.00', '95.00', '96.00',
       '97.00', '98.00', '?'], dtype=object)

In [71]:
Auto = pd.read_csv('/content/drive/MyDrive/data/Auto.data',
                    na_values=['?'],
                    sep=r"\s+")

In [72]:
Auto.shape # Auto.shape attribute tells us that the data has 397 observations or rows and 9 columns.

(397, 9)

In [74]:
num_rows = Auto.isna().any(axis=1).sum() # This count the rows with missing values and we print it nextly.
print(f"Number of rows with missing values: {num_rows}")

Number of rows with missing values: 5


In [76]:
# Count rows that contain only missing values
number = Auto.isna().all(axis=1).sum()
print(number)

0


In [77]:
# Get the actual rows with missing values
rows_with_missing_values = Auto[Auto.isna().any(axis=1)]
print(rows_with_missing_values)

      mpg  cylinders  displacement  horsepower  weight  acceleration  year  \
32   25.0          4          98.0         NaN  2046.0          19.0    71   
126  21.0          6         200.0         NaN  2875.0          17.0    74   
330  40.9          4          85.0         NaN  1835.0          17.3    80   
336  23.6          4         140.0         NaN  2905.0          14.3    80   
354  34.5          4         100.0         NaN  2320.0          15.8    81   

     origin                  name  
32        1            ford pinto  
126       1         ford maverick  
330       2  renault lecar deluxe  
336       1    ford mustang cobra  
354       2           renault 18i  
